categories:
  -
    labels:
      - feature
      - enhancement
    title: "🚀 Features"
  -
    labels:
      - fix
      - bugfix
      - bug
    title: "🐛 Bug Fixes"
  -
    label: chore
    title: Maintenance
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
name-template: "v$NEXT_PATCH_VERSION 🚀"
tag-template: v$NEXT_PATCH_VERSION
template: |
    ## Changes

    $CHANGES

    ## rbac-tool
    Generate Role or ClusterRole resource while reducing the use of wildcards.

    `rbac-tool` read from the Kubernetes discovery API the available API Groups and resources,
    and based on the command line options, generate an explicit Role/ClusterRole that avoid wildcards

    Example:

    ```shell script
    rbac-tool  gen --generated-type=Role --deny-resources=secrets.,daemonsets.apps --allowed-verbs=get,list --allowed-groups=,apps,networking.k8s.io
    ```
