name-template: 'v$NEXT_PATCH_VERSION 🚀'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES 

  Generate Role or ClusterRole resource while reducing the use of wildcards.

  `rbac-minimizer` read from the Kubernetes discovery API the available API Groups and resources,
  and based on the command line options, generate an explicit Role/ClusterRole that avoid wildcards

  Example - 
  ```shell script
  rbac-minimizer  gen --generated-type=Role --deny-resources=secrets.,daemonsets.apps --allowed-verbs=get,list --allowed-groups=,apps,networking.k8s.io
  ```


