categories:
  -
    labels:
      - feature
      - enhancement
    title: "🚀 Features"
  -
    labels:
      - fix
      - bugfix
      - bug
    title: "🐛 Bug Fixes"
  -
    label: chore
    title: Maintenance
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
name-template: "v$NEXT_PATCH_VERSION 🚀"
tag-template: v$NEXT_PATCH_VERSION
template: |
    ## Changes

    $CHANGES

    ## rbac-tool
    A collection of Kubernetes RBAC tools to sugar coat Kubernetes RBAC complexity

    Examples:

    ```shell script
    rbac-tool  lookup
    ```

    ```shell script
    rbac-tool  viz
    ```

    ```shell script
    rbac-tool  gen --generated-type=Role --deny-resources=secrets.,daemonsets.apps --allowed-verbs=get,list --allowed-groups=,apps,networking.k8s.io
    ```

