apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: rbac-tool
spec:
  version: {{ .TagName }}
  platforms:
    - bin: rbac-tool
      {{addURIAndSha "https://github.com/alcideio/rbac-tool/releases/download/{{ .TagName }}/rbac-tool_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
      files:
        - from: rbac-tool
          to: rbac-tool
      selector:
        matchLabels:
          os: linux
          arch: amd64

    - bin: rbac-tool
      files:
        - from: rbac-tool
          to: rbac-tool

      {{addURIAndSha "https://github.com/alcideio/rbac-tool/releases/download/{{ .TagName }}/rbac-tool_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
      selector:
        matchLabels:
          os: darwin
          arch: amd64

    - bin: rbac-tool
      {{addURIAndSha "https://github.com/alcideio/rbac-tool/releases/download/{{ .TagName }}/rbac-tool_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
      files:
        - from: rbac-tool.exe
          to: rbac-tool.exe
      selector:
        matchLabels:
          os: windows
          arch: amd64

  shortDescription: Kubernetes RBAC Power Toys - Visualize, Analyze, Generate & Query
  homepage: https://github.com/alcideio/rbac-tool
  description: |
    This plugin is a collection of Kubernetes RBAC power tools to sugar coat Kubernetes RBAC complexity

    Available Commands:
      auditgen        Generate RBAC policy from Kubernetes audit events
      generate        Generate Role or ClusterRole and reduce the use of wildcards
      lookup          RBAC Lookup by subject (user/group/serviceaccount) name
      policy-rules    RBAC List Policy Rules For subject (user/group/serviceaccount) name
      version         Print rbac-tool version
      visualize       A RBAC visualizer
      who-can         Shows which subjects have RBAC permissions to perform an action

    Flags:
      -h, --help      help for rbac-tool
      -v, --v Level   number for the log level verbosity